version: '3'
services:
  nginx:
    build: containers/nginx
    volumes:
      - web
    ports:
      - 80:80
    depends_on:
      - web
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Blackwing84s
      MYSQL_DATABASE: Admin
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec  puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: production
