version: '3'
services:
  nginx:
    build: containers/nginx
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec  puma -C config/puma.rb
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: production
